name: 'helm-package'
description: Package helm chart

inputs:
  chart-path:
    required: false
    description: set custom chart path
    default: './charts'
runs:
  using: composite
  steps:
    - name: helm package
      run: helm package ${{ inputs.chart-path }}
#      run: |
#        ls -la .
#        echo "------"
#        ls -la ${{ inputs.chart-path }}
#        helm dependency build
#        helm lint
#        helm init --client-only
#        helm package ${{ inputs.chart-path }}
      shell: bash
#      working-directory: ${{ inputs.chart-path }}
