# Based on Helm-docs utility https://github.com/norwoodj/helm-docs
name: 'helm-docs'
description: Generate Helm docs

inputs:
  chart-path:
    required: false
    description: set custom chart path
    default: './'
  git-token:
    description: the git token used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: true
    default: ''
  version:
    description: set version
    required: false
    default: ''
  docs-version:
    description: set version
    required: false
    default: '1.11.0'
  git-username:
    description: the git username used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: false
    default: 'Actions Bot'
  git-author-name:
    description: the user name to git commit
    required: false
    default: ''
  git-author-email:
    description: the user email to git commit
    required: false
    default: 'no-reply@no-reply.users.github.com'
runs:
  using: composite
  steps:
    - name: helm package
      env:
        GITHUB_TOKEN: ${{ inputs.git-token }}
      run: |
        wget https://github.com/norwoodj/helm-docs/releases/download/v${{ inputs.docs-version }}/helm-docs_${{ inputs.docs-version }}_Linux_x86_64.deb
        sudo apt install -y ./helm-docs_${{ inputs.docs-version }}_Linux_x86_64.deb
        rm -f ./helm-docs_${{ inputs.docs-version }}_Linux_x86_64.deb
        helm-docs ${{ inputs.chart-path }}
        git config --global user.name ${{ inputs.git-username }}
        git config --global user.email ${{ inputs.git-author-email }}
        git add -A
        git commit -m "Version ${{ inputs.version }} update"
        git push
      shell: bash