# Based on Helm-docs utility https://github.com/norwoodj/helm-docs
name: 'release-tag'
description: Generate Helm docs

inputs:
  path:
    required: false
    description: set custom chart path
    default: './'
  git-token:
    description: the git token used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: true
    default: ''
  version:
    description: set version
    required: false
    default: ''
  git-username:
    description: the git username used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: false
    default: 'Actions Bot'
  git-author-name:
    description: the user name to git commit
    required: false
    default: ''
  git-author-email:
    description: the user email to git commit
    required: false
    default: 'no-reply@no-reply.users.github.com'
runs:
  using: composite
  steps:
    - name: release tag
      env:
        GITHUB_TOKEN: ${{ inputs.git-token }}
      run: |
        git config --global user.name ${{ inputs.git-username }}
        git config --global user.email ${{ inputs.git-author-email }}
        git add -A
        git commit -m "Release ${{ inputs.version }}"
        git tag -fa -m "Release ${{ inputs.version }}" ${{ inputs.version }}
        git push origin ${{ inputs.version }}
      shell: bash