name: 'helm-release'
description: Release helm chart

inputs:
  chart-path:
    required: false
    description: set custom chart path
    default: './'
  release-path:
    required: true
    description: set RELEASE or SNAPSHOTS dir
    default: 'snapshots'
  git-token:
    description: the git token used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: false
    default: ''
  git-username:
    description: the git username used to operate on the git repository. If not specified it's loaded from the git credentials file
    required: false
    default: ''
  git-author-name:
    description: the user name to git commit
    required: false
    default: ''
  git-author-email:
    description: the user email to git commit
    required: false
    default: ''
runs:
  using: composite
  steps:
    - name: Checkout repo
      uses: actions/checkout@v3
      with:
        path: 'dst'
        ref: 'main'
        repository:
    - name: helm release
      run: |
        helm repo index . --merge ./dst/${{ inputs.release-path }}/index.yaml --url https://github.com/volkotyk/examples/${{ inputs.release-path }}
        cp -f index.yaml ./dst/${{ inputs.release-path }}/
        cp -f *.tgz ./dst/${{ inputs.release-path }}/
        cd ./dst
        git add -A
        git config --global user.name "actions bot"
        git config --global user.email "noanswer@example.com"
        git commit -m "add new chart GITHUB_ACTION_REPOSITORY"
        git push
      shell: bash
      working-directory: ${{ inputs.chart-path }}
      env:
        GIT_USERNAME: ${{ inputs.git-username }}
        GIT_TOKEN: ${{ inputs.git-token }}
        GIT_AUTHOR_NAME: ${{ inputs.git-author-name || inputs.git-username }}
        GIT_AUTHOR_EMAIL: ${{ inputs.git-author-email }}